### ISSUE TITLE
Newlines and comments breaks tree structure

### ISSUE THREAD

**Issue by thekid** [xp-forge/yaml#2]
If we add a newline or comment (or both) before the key *dropdown* in the following YAML document, the parser puts the dropdown tree in the top-level document instead of as a subnode of context:

## Works

```yaml
context:
  texts:
    login:
      text: {"en": "Login", "de": "Login"}
    logout:
      text: {"en": "Logout", "de": "Logout"}
  dropdown:
    settings:
      url: /config/
      text: {"en": "Settings", "de": "Einstellungen"}
```

## Broken

```yaml
context:
  texts:
    login:
      text: {"en": "Login", "de": "Login"}
    logout:
      text: {"en": "Logout", "de": "Logout"}

  dropdown:
    settings:
      url: /config/
      text: {"en": "Settings", "de": "Einstellungen"}
```
